[package]
name = "tis-100-superoptimizer"
version = "0.1.0"
authors = ["Daan van Berkel <daan.v.berkel.1980@gmail.com>"]

[dependencies]
yaml-rust = "0.3.3"

[lib]
name = "tis_100_superoptimizer"
path = "src/lib.rs"

[[bin]]
name = "optimize"
path = "src/bin/optimize.rs"
